"""autogenerated migration

Revision ID: 6289e718b8e6
Revises: c5e2411f1288
Create Date: 2024-11-06 01:07:26.642884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6289e718b8e6'
down_revision: Union[str, None] = 'c5e2411f1288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'weatherapi_air_quality', ['id'])
    op.create_unique_constraint(None, 'weatherapi_current_condition', ['id'])
    op.create_unique_constraint(None, 'weatherapi_current_weather', ['id'])
    op.create_unique_constraint(None, 'weatherapi_forecast_json', ['id'])
    op.create_unique_constraint(None, 'weatherapi_location', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weatherapi_location', type_='unique')
    op.drop_constraint(None, 'weatherapi_forecast_json', type_='unique')
    op.drop_constraint(None, 'weatherapi_current_weather', type_='unique')
    op.drop_constraint(None, 'weatherapi_current_condition', type_='unique')
    op.drop_constraint(None, 'weatherapi_air_quality', type_='unique')
    # ### end Alembic commands ###
