[default]

celery_broker_url = "amqp://guest:guest@localhost:5672/"
celery_backend_url = "redis://localhost:6379/0"

weatherapi_api_key = ""

db_password = ""

[celery]

celery_broker_url = "<your-rabbitmq-connection-string>"
celery_backend_url = "<your-redis-connection-string>"

[weatherapi]

weatherapi_api_key = "<your-weatherapi-key>"

[database]

# db_password = "postgres"
