[default]

celery_broker_url = "amqp://guest:guest@localhost:5672/"
celery_backend_url = "redis://localhost:6379/0"

[celery]

celery_broker_url = "<your-rabbitmq-connection-string>"
celery_backend_url = "<your-redis-connection-string>"
