[default]

log_level = "INFO"
celery_log_level = "info"

weatherapi_location_name = "London"

db_type = "sqlite"
db_drivername = "sqlite+pysqlite"
db_username = ""
# Set in .secrets.toml
# db_password = ""
db_host = ""
db_port = ""
db_database = "db.sqlite3"
db_echo = false

[logging]

# log_level = "DEBUG"

[celery]

# celery_log_level = "debug"

[weatherapi]

# weatherapi_location_name = "<your-location>"

[database]

db_type = "sqlite"
db_drivername = "sqlite+pysqlite"
db_username = ""
# Set in .secrets.toml
# db_password = ""
db_host = ""
db_port = ""
db_database = "db.sqlite3"
db_echo = false

# db_type = "postgres"
# db_drivername = "postgresql+psycopg2"
# db_username = "postgres"
# # Set in .secrets.toml
# # db_password = ""
# db_host = "localhost"
# db_port = 5432
# db_database = "weather"
# db_echo = false
