[default]

log_level = "INFO"
celery_log_level = "info"

weatherapi_location_name = "London"

[logging]

# log_level = "DEBUG"

[celery]

# celery_log_level = "debug"

[weatherapi]

# weatherapi_location_name = "<your-location>"
